import '../models/canteen_models.dart';

class MockData {
  static final List<Canteen> canteens = [
    Canteen(
      id: 'canteen-01',
      name: 'Main Food Court (Central)',
      code: 'MAIN101',
      location: 'Central Block, Ground Floor',
      rating: 4.8,
      averagePrepMinutes: 10,
      isOpen: true,
      categories: ['All', 'Meals', 'Snacks', 'Beverages', 'South Indian', 'Chinese', 'Desserts'],
      openingHours: '7:30 AM - 8:30 PM',
    ),
    Canteen(
      id: 'canteen-02',
      name: 'Tech Park Cafe & Bites',
      code: 'TECH202',
      location: 'Engineering Block 3, 1st Floor',
      rating: 4.6,
      averagePrepMinutes: 8,
      isOpen: true,
      categories: ['All', 'Quick Bites', 'Beverages', 'Sandwiches', 'Shakes'],
      openingHours: '8:30 AM - 6:00 PM',
    ),
    Canteen(
      id: 'canteen-03',
      name: 'Green Oasis Healthy Spot',
      code: 'GREEN303',
      location: 'Sports Complex Plaza',
      rating: 4.7,
      averagePrepMinutes: 12,
      isOpen: true,
      categories: ['All', 'Salads', 'Fresh Juices', 'Smoothies', 'Diet Bowls'],
      openingHours: '8:00 AM - 7:00 PM',
    ),
  ];

  static final List<MenuItem> defaultMenuItems = [
    // Main Food Court Items
    MenuItem(
      id: 'item-01',
      canteenId: 'canteen-01',
      name: 'Crispy Butter Masala Dosa',
      description: 'Golden roasted fermented crepe filled with spiced potato masala, served with 3 fresh chutneys & piping sambar.',
      price: 65,
      category: 'South Indian',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 7,
      rating: 4.9,
      isBestSeller: true,
      spicyLevel: 1,
      calories: '320 kcal',
    ),
    MenuItem(
      id: 'item-02',
      canteenId: 'canteen-01',
      name: 'Paneer Butter Masala Bowl',
      description: 'Rich creamy tomato gravy with soft cottage cheese cubes, served with 2 warm butter rotis and aromatic jeera rice.',
      price: 110,
      category: 'Meals',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 12,
      rating: 4.8,
      isBestSeller: true,
      spicyLevel: 1,
      calories: '520 kcal',
    ),
    MenuItem(
      id: 'item-03',
      canteenId: 'canteen-01',
      name: 'Schezwan Veg Fried Rice',
      description: 'Wok-tossed basmati rice with crunchy carrots, cabbage, capsicum in fiery homemade Schezwan sauce.',
      price: 90,
      category: 'Chinese',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 9,
      rating: 4.6,
      isBestSeller: false,
      spicyLevel: 2,
      calories: '440 kcal',
    ),
    MenuItem(
      id: 'item-04',
      canteenId: 'canteen-01',
      name: 'Classic Chicken Biryani Combo',
      description: 'Dum-cooked fragrant basmati rice layered with succulent marinated chicken, boiled egg, mirchi ka salan & raita.',
      price: 140,
      category: 'Meals',
      isVeg: false,
      isAvailable: true,
      prepTimeMinutes: 10,
      rating: 4.9,
      isBestSeller: true,
      spicyLevel: 2,
      calories: '610 kcal',
    ),
    MenuItem(
      id: 'item-05',
      canteenId: 'canteen-01',
      name: 'Masala Chai & Hot Samosa (2 pcs)',
      description: 'Freshly brewed aromatic ginger-cardamom milk tea with two crispy Punjabi potato samosas and sweet tamarind dip.',
      price: 45,
      category: 'Snacks',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 4,
      rating: 4.8,
      isBestSeller: true,
      spicyLevel: 1,
      calories: '280 kcal',
    ),
    MenuItem(
      id: 'item-06',
      canteenId: 'canteen-01',
      name: 'Cold Coffee with Ice Cream',
      description: 'Thick creamy blended espresso topped with a scoop of Madagascar vanilla ice cream and chocolate drizzle.',
      price: 55,
      category: 'Beverages',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 5,
      rating: 4.7,
      isBestSeller: false,
      spicyLevel: 0,
      calories: '260 kcal',
    ),
    MenuItem(
      id: 'item-07',
      canteenId: 'canteen-01',
      name: 'Chole Bhature Platter',
      description: 'Two fluffy balloon bhatures served with rich Punjabi spiced chickpea curry, pickled onions, and mint dip.',
      price: 85,
      category: 'Meals',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 11,
      rating: 4.7,
      isBestSeller: false,
      spicyLevel: 2,
      calories: '560 kcal',
    ),
    MenuItem(
      id: 'item-08',
      canteenId: 'canteen-01',
      name: 'Hot Gulab Jamun (2 pcs)',
      description: 'Warm melt-in-the-mouth khoya dumplings soaked in rose and saffron infused sugar syrup.',
      price: 35,
      category: 'Desserts',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 3,
      rating: 4.9,
      isBestSeller: false,
      spicyLevel: 0,
      calories: '210 kcal',
    ),

    // Tech Park Cafe Items
    MenuItem(
      id: 'item-09',
      canteenId: 'canteen-02',
      name: 'Grilled Cheese & Corn Sandwich',
      description: 'Toasted whole wheat bread stuffed with melted mozzarella, sweet corn kernels, and Italian herb seasoning.',
      price: 70,
      category: 'Sandwiches',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 6,
      rating: 4.7,
      isBestSeller: true,
      spicyLevel: 0,
      calories: '340 kcal',
    ),
    MenuItem(
      id: 'item-10',
      canteenId: 'canteen-02',
      name: 'Crispy Peri-Peri French Fries',
      description: 'Double-fried crunchy potato fingers generously tossed with spicy African peri-peri seasoning and garlic mayo dip.',
      price: 60,
      category: 'Quick Bites',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 5,
      rating: 4.8,
      isBestSeller: true,
      spicyLevel: 2,
      calories: '310 kcal',
    ),
    MenuItem(
      id: 'item-11',
      canteenId: 'canteen-02',
      name: 'KitKat Monster Thickshake',
      description: 'Heavy dairy milkshake loaded with crushed KitKat wafers, Belgian chocolate syrup, and whipped cream.',
      price: 80,
      category: 'Shakes',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 6,
      rating: 4.9,
      isBestSeller: true,
      spicyLevel: 0,
      calories: '420 kcal',
    ),
    MenuItem(
      id: 'item-12',
      canteenId: 'canteen-02',
      name: 'Chicken Tikka Club Sandwich',
      description: 'Triple-layer toasted sandwich stuffed with tandoori shredded chicken, crisp lettuce, cheese slice, and honey mustard.',
      price: 95,
      category: 'Sandwiches',
      isVeg: false,
      isAvailable: true,
      prepTimeMinutes: 8,
      rating: 4.6,
      isBestSeller: false,
      spicyLevel: 1,
      calories: '480 kcal',
    ),

    // Green Oasis Healthy Items
    MenuItem(
      id: 'item-13',
      canteenId: 'canteen-03',
      name: 'High-Protein Sprout & Tofu Salad',
      description: 'Organic sprouted moong, steamed tofu cubes, cherry tomatoes, cucumbers with lemon vinaigrette & roasted flaxseeds.',
      price: 90,
      category: 'Salads',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 7,
      rating: 4.8,
      isBestSeller: true,
      spicyLevel: 0,
      calories: '220 kcal',
    ),
    MenuItem(
      id: 'item-14',
      canteenId: 'canteen-03',
      name: 'Fresh Detox Green Smoothie',
      description: 'Cold-pressed blend of baby spinach, green apple, cucumber, chia seeds, and coconut water.',
      price: 75,
      category: 'Smoothies',
      isVeg: true,
      isAvailable: true,
      prepTimeMinutes: 4,
      rating: 4.6,
      isBestSeller: false,
      spicyLevel: 0,
      calories: '140 kcal',
    ),
  ];

  static List<OrderModel> getInitialSampleOrders() {
    final now = DateTime.now();
    return [
      OrderModel(
        id: 'ord-101',
        tokenNumber: 'TK-108',
        canteenId: 'canteen-01',
        canteenName: 'Main Food Court (Central)',
        studentId: 'STU9421',
        studentName: 'Alex Mercer',
        studentPhone: '+91 98765 43210',
        totalAmount: 175,
        status: OrderStatus.preparing,
        pickupType: 'asap',
        paymentMethod: 'Campus Wallet',
        specialInstructions: 'Make the Dosa extra crisp please!',
        createdAt: now.subtract(const Duration(minutes: 6)),
        estimatedReadyTime: now.add(const Duration(minutes: 5)),
        items: [
          OrderItem(
            menuItemId: 'item-01',
            itemName: 'Crispy Butter Masala Dosa',
            price: 65,
            quantity: 1,
            isVeg: true,
          ),
          OrderItem(
            menuItemId: 'item-02',
            itemName: 'Paneer Butter Masala Bowl',
            price: 110,
            quantity: 1,
            isVeg: true,
          ),
        ],
      ),
      OrderModel(
        id: 'ord-102',
        tokenNumber: 'TK-109',
        canteenId: 'canteen-01',
        canteenName: 'Main Food Court (Central)',
        studentId: 'STU8834',
        studentName: 'Priya Sharma',
        studentPhone: '+91 98123 45678',
        totalAmount: 140,
        status: OrderStatus.placed,
        pickupType: 'scheduled',
        scheduledTime: '1:30 PM',
        paymentMethod: 'UPI',
        specialInstructions: 'Extra raita with biryani',
        createdAt: now.subtract(const Duration(minutes: 2)),
        estimatedReadyTime: now.add(const Duration(minutes: 12)),
        items: [
          OrderItem(
            menuItemId: 'item-04',
            itemName: 'Classic Chicken Biryani Combo',
            price: 140,
            quantity: 1,
            isVeg: false,
          ),
        ],
      ),
      OrderModel(
        id: 'ord-103',
        tokenNumber: 'TK-105',
        canteenId: 'canteen-01',
        canteenName: 'Main Food Court (Central)',
        studentId: 'STU7712',
        studentName: 'Rohan Verma',
        studentPhone: '+91 97654 32109',
        totalAmount: 100,
        status: OrderStatus.ready,
        pickupType: 'asap',
        paymentMethod: 'Campus Wallet',
        createdAt: now.subtract(const Duration(minutes: 15)),
        estimatedReadyTime: now.subtract(const Duration(minutes: 1)),
        items: [
          OrderItem(
            menuItemId: 'item-05',
            itemName: 'Masala Chai & Hot Samosa (2 pcs)',
            price: 45,
            quantity: 1,
            isVeg: true,
          ),
          OrderItem(
            menuItemId: 'item-06',
            itemName: 'Cold Coffee with Ice Cream',
            price: 55,
            quantity: 1,
            isVeg: true,
          ),
        ],
      ),
    ];
  }
}
